### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [haptork/easyLambda#2]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/haptork/easyLambda/blob/d13adac116d7c1693d7ade9eab248bd2094e60bc/Makefile#L1) so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/)
- [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction)

**Comment by haptork** [comment]
Thank you for the suggestion. I've added a basic CMAKE file. Now the library has a serial mode that does not require MPI and boost counterparts, cmake helps in that a lot. Cmake also helps with Travis-CI and codecov.

In future I'm looking to improve this by:

- Refactoring CMake code to more modern targets style.
- Adding code coverage with both serial and parallel builds.

Help in these two areas would be much appreciated.

**Comment by elfring** [comment]
Thanks for [your software extension](https://github.com/haptork/easyLambda/commit/b914ca571652fae2df2e83e86cce814f9d6c3227 "Adding basic CMAKE file").
