### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [haptork/easyLambda#3]
I would like to point out that identifiers like "[`__ezl__EZL__H__`](https://github.com/haptork/easyLambda/blob/d13adac116d7c1693d7ade9eab248bd2094e60bc/include/ezl.hpp#L12)" and "[`__FILTERBUILDER_EZL_H__`](https://github.com/haptork/easyLambda/blob/f17dde21f607bb973cab80c4a5fef74bec39fbf4/include/ezl/builder/FilterBuilder.hpp#L12)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/haptork/easyLambda/commit/18d54c2a11262a2184ad24dd4c6d94c945fdfd28).

**Comment by haptork** [comment]
Thanks for the suggestion. :)
