### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [haptork/easyLambda#4]
Would you like to [replace any double quotes](https://github.com/haptork/easyLambda/blob/d13adac116d7c1693d7ade9eab248bd2094e60bc/include/ezl.hpp#L18) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by haptork** [comment]
The opinions on the SO link are quite differing. The most convincing to me is:
- double quotes when giving relative path.
- angle brackets when in include path.

There are opinions that say it helps distinguish system headers from library headers although I don't think this should be the case. 

Is there anything more to it?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html) from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf) in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) for header files of your software?

**Comment by haptork** [comment]
I totally agree with using angular brackets in examples, tests and for any code that uses the library.

The confusion is for library headers. For e.g. [ezl.hpp](../tree/master/include/ezl.hpp) can have relative paths and double quotes or it can have angular brackets.

I think that its better to have angular brackets everywhere for consistency but just some clarification before going ahead. :)

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
- How do you think about to follow the inclusion style from [the class library "Boost"](http://www.boost.org/)?

**Comment by haptork** [comment]
I just checked with Boost 1.54 that uses double quotes everywhere and 1.60 that uses angle brackets everywhere.

[Commit](https://github.com/haptork/easyLambda/commit/99bcdb85a4aa32d3469e5cac5fc6c83bb542be8a) for using angle brackets consistently everywhere.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/haptork/easyLambda/commit/99bcdb85a4aa32d3469e5cac5fc6c83bb542be8a).

**Comment by haptork** [comment]
Thanks for the very useful suggestions and informative links.
