### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [haptork/easyLambda#5]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) in a function like [the destructor for the class "DumpFile"](https://github.com/haptork/easyLambda/blob/d13adac116d7c1693d7ade9eab248bd2094e60bc/include/ezl/mapreduce/DumpFile.hpp#L51).

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/haptork/easyLambda/commit/c7ba4f6fb7d1a74f82abed94cb3281c61dba9e01).

**Comment by haptork** [comment]
Thanks for pointing this out. :)
