### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [haptork/easyLambda#6]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/haptork/easyLambda/blob/d13adac116d7c1693d7ade9eab248bd2094e60bc/examples/demoReadFile.cpp#L20)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by haptork** [comment]
Thanks for the informative links.

I completely agree that an application should have a cap of try and catch with an error message. However, the examples are meant to be a quick and concise way to show functionalities and capabilities of the library. Hence, the try-catch cap is omitted. 

In the same light, I don't think use of assert for input bounds is an ideal choice for an application but I am not sure if it's bad in examples as well. 

Is it more about programming style or do you think try-catch ommision can have some bad consequences in execution of examples?

**Comment by elfring** [comment]
- Does the the "try-catch ommision" (in "examples") result in a higher probability that other software developers will also occasionally "overlook" the usefulness of these statements in their main() functions?
- Would you like to [reconsider consequences from implementation-defined behaviour](http://stackoverflow.com/questions/5557555/raii-and-stack-unwinding)?

**Comment by haptork** [comment]
Exception handling is not enabled in MPI programs by default. [link](http://stackoverflow.com/questions/3762728/am-i-allowed-to-throw-an-exception-inside-mpi-parallelized-code). Even after catching the exception it is required to abort the program to avoid deadlock.

The main function for pi.cpp example with exception handling is:

``` cpp
int main(int argc, char *argv[]) {
  boost::mpi::environment env(argc, argv, false);  // false to enable exception-handlers
  try {
    valueOfPi(argc, argv);
  } catch (const std::exception& ex) {
    std::cerr<<"error: "<<ex.what()<<'\n';
    env.abort(1);  
  } catch (...) {
    std::cerr<<"unknown exception\n";
    env.abort(2);  
  }
  return 0;
}
```

This is a better release / production code but might look overly complicated to someone who want to understand the basics of ezl and try writing some code. However, I agree on the point that it encourages good programming practices as a whole.

**Comment by haptork** [comment]
Added exception handling with this [commit](../commit/4c94aeb2591b1e2405e0e12750c29278bcbd64d9).

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/haptork/easyLambda/commit/4c94aeb2591b1e2405e0e12750c29278bcbd64d9#diff-95c3d1883795b6bf63d6cee4a35dbffbR45).
