### ISSUE TITLE
not surpport vc2015?

### ISSUE THREAD

**Issue by qicosmos** [haptork/easyLambda#9]
does thie project surpport vc2015 on windows?

**Comment by haptork** [comment]
I have not tried yet as I personally work on Linux or Mac.
Since, vc2015 supports almost all the features of C++14, I don't think there will be any major issue.
Let me know if you tried it.

I will try to run it with vc2015 and will post the update soon.

**Comment by qicosmos** [comment]
I tryed but failed, compile error: can not find glob.h.

**Comment by haptork** [comment]
Thank you. Following are some details and workaround for the error.
- glob.h is included in ezl/helper/vglob.hpp
- vglob.hpp is used in algorithms/fromFile.hpp and algorithms/io.hpp to read data from multiple files with name given as string pattern.
- vglob.hpp is not used in ezl core anywhere.
- try compiling example demoRise.hpp after commenting `#include <ezl/algorithms/io.hpp>`.
  or 
  replace "vglob.hpp" with [this file](https://gist.githubusercontent.com/haptork/075f2d32865ce59904bd41765ff7f331/raw/19c14da8ecd1fac97b65ab0ec56a58524afaa67f/vglob.hpp).

I will update the vglob.hpp in the repo after testing it. Let me know if there are some other issues after fixing this.

**Comment by qicosmos** [comment]
but i can not find the glob.h in the project, is it a linux file ?

**Comment by qicosmos** [comment]
Let me hava a try, replace the file.

**Comment by qicosmos** [comment]
I can't use boost.mpi, i use boost1.60 and vs2015, but i can't compile the mpi libary, lack of the lib libboost_mpi-vc140-mt-gd-1_60.lib.
I have installed mpich, but sitll can't build the lib, i don't konw why.

**Comment by haptork** [comment]
I'm assuming that you are able to run mpic++ / mpicxx and mpirun.

Most probably the problem is that boost_mpi is not compiling while building boost.  
When building boost, make sure you add `using mpi ;` in the project-config.jam as directed in this [link](http://www.boost.org/doc/libs/1_61_0/doc/html/mpi/getting_started.html).

**Comment by haptork** [comment]
The library now has a serial mode that does not require MPI and boost counterparts. It also has a CMake config. I think with these two it might now be easier to test builds on MSVC especially with glob file replaced as mentioned above. Building it in serial does not require boost libs. If it doesn't work now that please let me know.
